spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexus_ledger
    username: nexus_user
    password: nexus_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # O Liquibase assume o controle total
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml